### ISSUE TITLE
Can't even run emborg help.

### ISSUE THREAD

**Issue by gaia** [KenKundert/emborg#11]
`# emborg help`

```
Traceback (most recent call last):
  File "/usr/local/bin/emborg", line 7, in <module>
    from emborg.main import main
  File "/usr/local/lib/python3.5/dist-packages/emborg/__init__.py", line 4, in <module>
    from .settings import Settings as Emborg
  File "/usr/local/lib/python3.5/dist-packages/emborg/settings.py", line 112
    f'Configuration directory created: {parent!s}.',
                                                  ^
SyntaxError: invalid syntax
```

emborg was installed as `pip3 install emborg`, not `pip3 install --user emborg` because doing so, as root for install and as root to run, yield nothing.

Could this be because borg was installed as a single binary?

```
/usr/local/bin/borg -> /folder/where/borg-binary-is/borg-linux64
```

**Comment by KenKundert** [comment]
Emborg requires Python3.6 or better.

**Comment by gaia** [comment]
Debian 9.9 latest is Python 3.5.3, and I don't want to mess with it. Thank you Ken. Happy 4th!
